- name: print the names
  hosts: local
  connection: local
  tasks:
  - name: print names using loops
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
    - iMac
    - Macbook
    - Iphone


