- name: loops
  hosts: local
  become: yes
  tasks:
  - name: installing packages with loops
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - git
    - tree
    - gcc




